apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "netflix-helm.fullname" . }}
  labels:
    {{- include "netflix-helm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "netflix-helm.selectorLabels" . | nindent 6 }}
  {{- if eq .Values.strategy.type "RollingUpdate" }}
  strategy:
    type: {{ .Values.strategy.type }}
    {{- with .Values.strategy.rollingUpdate }}
    rollingUpdate:
    {{- toYaml . | nindent 9 }}
    {{- end}}
  {{- end }}    
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "netflix-helm.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "netflix-helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.ports.name }}
              containerPort: {{ .Values.ports.containerPort }}
              protocol: {{ default "TCP" .Values.ports.type }}
           
 
